### ISSUE TITLE
Doubt regarding update query in the `crud.py` file

### ISSUE THREAD

**Issue by dhruv-ahuja** [dudikbender/fast-graph#1]
Hello, I have been using your project as a reference to understand how neo4j works better and it has been a big help to me thus far.

I had a doubt regarding the `update node` aspect in the application [here](https://github.com/dudikbender/fast-graph/blob/3c1863a0b718b039ef2cf03aa134c266853b548d/app/graph/crud.py#L54).

Will the backslashes `f'new_node.{key}=\'{value}\''` near the value variable help escape characters and be secure from cypher injection attacks? 

I tried looking around but could not find a conclusive answer to the same. 
Thank you.

**Comment by dudikbender** [comment]
Hey. Yes, this has been resolved with parameterised queries - hope that helps.
