### ISSUE TITLE
question about neo4j connectivity

### ISSUE THREAD

**Issue by ritiksoni00** [dudikbender/fast-graph#4]
https://github.com/dudikbender/fast-graph/blob/main/app/utils/db.py#L7

you are importing this`neo4j_driver` variable where it's needed but it's not recommended as it's expensive to create.

do you have any other idea how can we not create it everytime?

**Comment by dudikbender** [comment]
This should be refactored into classes for db query and mutation, I agree (am actually working on an update to the entire package that includes this...). Could refactor so the driver instance is a class that is only initialised when called? (https://neo4j.com/developer/python/)

**Comment by ritiksoni00** [comment]
Hmm.. actually when I asked about this to chatGPT. it answered 
" it will not create a new instance of the driver as we are giving the same auth data" , so its basically means that it will use the already created instance of the driver.

**Comment by dudikbender** [comment]
Hahaha, chatGPT is the best authority I suppose.
